### ISSUE TITLE
Guide correction / Feature request

### ISSUE THREAD

**Issue by Pixelartist** [stefanjenkner/payback-activate#26]
Hello there,

I stumbled upon this and really like the idea. My idea was hosting this in docker on my NAS which uses ARMV7, so far I got a couple of issues with the docker build.
To check if the code in general is working I ran this on my dev machine and it error'ed out. It took a small dive in your code and found that the account in question needs to have the "ecoupon" option enabled (which I had not). After enabling this, the script ran and activated all coupons.

Would be great if you could adjust your readme to this. I will play around a bit with this and see if I can make this work on my NAS as well.

**Comment by stefanjenkner** [comment]
Hi @Pixelartist,

Thanks for bringing this up and +1 to enhance the documentation. Please feel free to contribute a PR with an updated `README.md` mentioning steps how to activate the eCoupon option.

Thanks! ✌️
