### ISSUE TITLE
Make the script run on Android/iOS

### ISSUE THREAD

**Issue by danieldur** [stefanjenkner/payback-activate#5]
Since most of the Payback activity is happenings on mobile devices, it would be really useful to have a solution that would run on mobile devices too.
I know iOS would not be as easy, but I mentioned it not to discriminate.
Thank you!

**Comment by stefanjenkner** [comment]
Thanks a lot for your feature requests! 

While there is less hope for a mobile version, a containerized version running a headless browser is actually planned. 5 years ago, this was already possible with an [older Python+Selenium based version](https://github.com/stefanjenkner/payback-activate/releases/1.0.0) running headless Firefox in a Docker container.

**Comment by stefanjenkner** [comment]
Update: [Version 2.1.0](https://github.com/stefanjenkner/payback-activate/releases/2.1.0) supports running the script headless in a container.

@rorar feel free to check out the latest version - I think this should be sufficient for your request 🤞 

@danieldur sorry for closing your initial request as won't fix! Maybe the containerized version run it automated/nightly?
